#!/bin/bash

DOMAIN=$1
ROOT_DIR="/var/www/$DOMAIN/public"
BLOCK="/etc/nginx/sites-available/$DOMAIN"

php -v > /dev/null 2>&1 || { 
  printf "====== PHP is not installed. Instalation Aborted! ======\n"; 
  exit 0; 
}

# Test if Nginx is installed
nginx -v > /dev/null 2>&1
NGINX_IS_INSTALLED=$?
if [ NGINX_IS_INSTALLED -eq 0 ]; then
  printf "====== NGINX is not installed. Begin installation ======\n"; 
  sudo apt-get update && sudo apt-get install nginx nginx-common nginx-core 
  sudo service nginx start
  printf "====== NGINX installed. ======\n";
fi

# Test if nginx H5BP is installed
if [ ! -d /etc/nginx/h5bp  ]; then
  printf "====== Begin installation of nginx h5bp ======\n"; 
  /etc/init.d/nginx stop
  cd /etc
  mv nginx nginx-old
  git clone https://github.com/Qoto/server-configs-nginx.git nginx
  /etc/init.d/nginx start
fi

# Test if HipHop is installed
hhvm --version > /dev/null 2>&1
HHVM_IS_INSTALLED=$?
if [ HHVM_IS_INSTALLED -eq 0 ]; then
  printf "====== HipHop is not installed. Begin installation ======\n"; 
  wget -O - http://dl.hhvm.com/conf/hhvm.gpg.key | sudo apt-key add -
  echo deb http://dl.hhvm.com/ubuntu trusty main | sudo tee /etc/apt/sources.list.d/hhvm.list
  sudo apt-get update
  sudo apt-get install hhvm
  sudo update-rc.d hhvm defaults
  sudo /usr/share/hhvm/install_fastcgi.sh
  printf "====== HipHop installed. ======\n"; 
fi

echo ">>> Installing $DOMAIN"

# Create the Document Root directory
sudo mkdir -p $ROOT_DIR

# Assign ownership to user account
# sudo chown -R $USER:$USER $ROOT_DIR

# Create the Nginx server block file:
sudo tee $BLOCK > /dev/null <<EOF 
server {
  # don't forget to tell on which port this server listens
  listen [::]:80;
  listen 80;

  # listen on the www host and redirect to the non-www host (declared below)
  server_name "~^www\.(.*)$";
  return 301 $scheme://$1$request_uri;
}

server {
  listen [::]:80;
  listen 80;
  
  # index
  index index.php index.html index.htm;
  
  # The host name to respond to
  server_name $DOMAIN;
  
  # Work With FastCGI
  location ~ \\.(hh|php)\$ {
    fastcgi_keep_conn on;
    fastcgi_pass   127.0.0.1:9000;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
    include        fastcgi_params;
  }

  # Path for static files
  root /var/www/$DOMAIN/public;

  #Specify a charset
  charset utf-8;

  # Custom 404 page
  error_page 404 /404.html;

  # Include the basic h5bp config set
  include h5bp/basic.conf;
}


EOF

# Link to make it available
sudo ln -s $BLOCK /etc/nginx/sites-enabled/

# Test configuration and reload if successful
sudo nginx -t && sudo service nginx reload
